### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by keanantf** [waylaidwanderer/DotaBuddy#15]
```
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@1.0.0
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@1.0.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN DotaBuddy No repository field.
npm WARN DotaBuddy No license field.
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.13.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tigger/DotaBuddy/npm-debug.log

```

```tigger@Tigger:~/DotaBuddy$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```

**Comment by waylaidwanderer** [comment]
Make sure you have at least Node 6.9.1 installed, then try again.

**Comment by keanantf** [comment]
```
tigger@Tigger:~$ nodejs --version
v4.2.6
```

Cant seem to upgrade
Ran every tutorial available on the internet

**Comment by keanantf** [comment]
still this: 

```tigger@Tigger:~/DotaBuddy$ npm install

> undefined postinstall /home/tigger/DotaBuddy
> install-app-deps

Installing app dependencies for arch x64 to /home/tigger/DotaBuddy/app

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.4.5 (node_modules/electron-builder/node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^1.0.0 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-osx@^1.0.0 (node_modules/7zip-bin/node_modules/7zip-bin-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-osx@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN DotaBuddy No repository field.
npm WARN DotaBuddy No license field.
tigger@Tigger:~/DotaBuddy$ npm start

> @ start /home/tigger/DotaBuddy
> gulp start

/home/tigger/DotaBuddy/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/tigger/DotaBuddy/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 7.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (/home/tigger/DotaBuddy/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/tigger/DotaBuddy/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tigger/DotaBuddy/node_modules/gulp-sass/index.js:187:21)

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/tigger/.nvm/versions/node/v6.9.1/bin/node" "/home/tigger/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'gulp start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tigger/DotaBuddy/npm-debug.log
```
```tigger@Tigger:~/DotaBuddy$ node -v
v6.9.1```


```tigger@Tigger:~/DotaBuddy$ nodejs --version
The program 'nodejs' is currently not installed. You can install it by typing:
sudo apt install nodejs```

```

I assume that means I dont have nodejs? yet i installed it using "nvm".

**Comment by waylaidwanderer** [comment]
The command is `node` not `nodejs`. Looks like you're on 6.9.1 now which is good. Try redownloading the project now that you've updated node, and rerun npm install.
